### ISSUE TITLE
Missing DrawKit framework

### ISSUE THREAD

**Issue by marinehero** [alexsanderkhitev/DeviceStatistic#1]
Where can I find the DrawKit framework you are using in DeviceStatistic? thx

**Comment by alexsanderkhitev** [comment]
Hello @marinehero . Do you mean a framework for charts?

**Comment by marinehero** [comment]
Hi @alexsanderkhitev, no it is the DeviceKit.framework i.e see this screenshot http://screencast.com/t/KQs4bVVSWZHP

**Comment by alexsanderkhitev** [comment]
@marinehero  I removed this framework. I used this my class for it 

`//
//  DrawKit.swift
//  DrawKit
//
//  Created by Alexsander  on 12/3/15.
//  Copyright © 2015 Alexsander Khitev. All rights reserved.
//

import UIKit
import Foundation

public class Arc {
    
    public init() { }
    
    public static let sharedInstance = Arc()
        
    public func addFigure(path: CGPath, fillColor: UIColor, strokeColor: UIColor, strokeStart: CGFloat, strokeEnd: CGFloat, lineWidth: CGFloat, miterLimit: CGFloat, lineDashPhase: CGFloat, layer: CALayer) {
        let shape = CAShapeLayer()
        shape.path = path
        shape.fillColor = fillColor.CGColor
        shape.strokeColor = strokeColor.CGColor
        shape.strokeStart = strokeStart
        shape.strokeEnd = strokeEnd
        shape.lineWidth = lineWidth
        shape.miterLimit = miterLimit
        shape.lineDashPhase = lineDashPhase
        layer.addSublayer(shape)
    }
    
    public func drawCircle(arcRadius: CGFloat, miniRadius: CGFloat, fillColor: UIColor, strokeColor: UIColor, view: UIView) {
                
    }
    

}`

**Comment by marinehero** [comment]
Hi @alexsanderkhitev... awesome! Thank You!
